### ISSUE TITLE
Please release latest bugfix

### ISSUE THREAD

**Issue by msiebeneicher** [x-cray/logrus-prefixed-formatter#18]
Please release a new version with the latest bugfix: https://github.com/x-cray/logrus-prefixed-formatter/commit/31b341217ca8d2c6958611c89032550fcd015df8

Currently we need to stick the version to the current master in glide.

**Comment by x-cray** [comment]
Here you go https://github.com/x-cray/logrus-prefixed-formatter/releases/tag/v0.5.0

**Comment by msiebeneicher** [comment]
Perfect! 👍 
I will directly switch back to the latest version! :)
