### ISSUE TITLE
Undefined: logrus.DefaultTimestampFormat

### ISSUE THREAD

**Issue by marcelomd** [x-cray/logrus-prefixed-formatter#20]
Hi,

I recently updated the dependencies of a project and got this error: `.go/src/github.com/x-cray/logrus-prefixed-formatter/formatter.go:178: undefined: logrus.DefaultTimestampFormat`

I believe it has to do with [this commit](https://github.com/sirupsen/logrus/commit/abee6f9b0679f8044f5fca552eb6a9691a55d4ac).

Just a heads up!

Thanks!

**Comment by x-cray** [comment]
Thanks for pointing out. Indeed, they made it private.
