### ISSUE TITLE
logrus removed IsTerminal()

### ISSUE THREAD

**Issue by dudeskeeroo** [x-cray/logrus-prefixed-formatter#22]
Hi, 

First ever issue, forgive any noobness please.

Logrus has made breaking changes (without bumping semantic version!). The `logrus.IsTerminal()` function has been removed and this breaks prefixed-formatter.

The logrus change can be seen [here](https://github.com/sirupsen/logrus/commit/e66f22976feaed4e0a6ab43bc2b9226be8b0b979) and `go get` fails for logrus-prefixed-formatter:

```
go get -u github.com/x-cray/logrus-prefixed-formatter
# github.com/x-cray/logrus-prefixed-formatter
../../../../../github.com/x-cray/logrus-prefixed-formatter/formatter.go:147: undefined: logrus.IsTerminal
```

The problem for prefixed-formatter is in [`formatter.go:147`](https://github.com/x-cray/logrus-prefixed-formatter/blob/master/formatter.go#L147)

A quick solution is to change [`formatter.go:147`](https://github.com/x-cray/logrus-prefixed-formatter/blob/master/formatter.go#L147) to 
```golang
f.isTerminal = f.checkIfTerminal(entry.Logger.Out)
```
and copy the private function `checkIfTerminal()` from logrus [`text_formatter.go:72`](https://github.com/sirupsen/logrus/blob/master/text_formatter.go#L72) into `formatter.go`.

```golang
func (f *TextFormatter) checkIfTerminal(w io.Writer) bool {
	switch v := w.(type) {
	case *os.File:
		return terminal.IsTerminal(int(v.Fd()))
	default:
		return false
	}
}
```
This introduces a dependency on golang.org/x/crypto/ssh/terminal

With these changes the test suite runs correctly as do my applications. I don't know enough about the guts of logrus and terminals to put a 100% guarantee on the soundness of this solution.

If there's anything else I can do, let me know.

**Comment by x-cray** [comment]
Quite a nicely crafted issue, probably because it's the first one =) It makes sense that they move towards official implementation. And will not be an issue to add `golang.org/x/crypto/ssh/terminal` dependency to `logrus-prefixed-formatter` as it's gonna be already present due to `logrus`.
