### ISSUE TITLE
Please create a tag for changes from PR #4

### ISSUE THREAD

**Issue by matlockx** [x-cray/logrus-prefixed-formatter#5]
Since there was a breaking change in logrus, can you please provide two tags? One before the change of #4 which points out that logrus <= 0.11.0 is supported and one that says that it is compatible with logrus >= 0.11.1 ? That would make live way easier for people like me, that are using tools like glide, because i do not have to search for commit hashes then ;)

Thanks

**Comment by x-cray** [comment]
Makes sense. I've added to pretty much all significant changes.

**Comment by matlockx** [comment]
👍
