### ISSUE TITLE
Multiline input gets quoted, with line feed characters escaped

### ISSUE THREAD

**Issue by bastienbc** [x-cray/logrus-prefixed-formatter#9]
Hi!

I have a multiline input to log (the content of a short file), and without your formatter,
it is written as I expect to.

But your formatter escapes the new line (\n) if I don't use colors.
It is the needsQuote part that does that I think...

Can you do anything for me?

**Comment by x-cray** [comment]
@bastienbc Quoting in this case is intended as otherwise it wouldn't be possible to parse such output with automatic tools which understand [logfmt](https://brandur.org/logfmt)

**Comment by bastienbc** [comment]
You are right.
It's just that because I use a multiwriter to write to both stdout and a file,
it didn't use the fancy color output...

I'll find an other way, thanks!
